obj-y				+= common.o addr-map.o irq.o pcie.o mpp.o \
	clock.o
obj-$(CONFIG_MACH_DOVE_DB)	+= dove-db-setup.o
obj-$(CONFIG_MACH_CM_A510)	+= cm-a510.o
obj-$(CONFIG_MACH_CUBOX)	+= cubox-setup.o
obj-$(CONFIG_FB_DOVE)		+= clcd.o
